export { default as H1 } from './H1'
export { default as H2 } from './H2'
export { default as Text } from './Text'
export { default as Button } from './Button'
export { default as ImageHeader } from './ImageHeader'
export { Sizes } from './Button'